In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!java --version

openjdk 11.0.28 2025-07-15
OpenJDK Runtime Environment (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

In [3]:
!pip list | grep pyspark

pyspark                               3.5.1

In [4]:
# Remove old Java
!apt-get remove openjdk-* -y

# Install OpenJDK 17
!apt-get update -q
!apt-get install openjdk-17-jdk -y

# Set JAVA_HOME
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

# Verify
!java -version

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'openjdk-11-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-18-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-21-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-19-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-8-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-7-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-testsupport' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-9-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-17-source' for glob 'openjdk-*'
Note, selecting 'openjdk-17-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-11-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-source' for glob 'openjdk-*'
Note, selecting 'openjdk-14-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-13-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-11-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-dcevm' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-12-jre-headless' for glob 'openjdk-*'
Package 'openjdk-6-jre-headless' is not installed, so not removed
Package 'openjdk-14-jre-headless' is not installed, so not removed
Package 'openjdk-13-jre-headless' is not installed, so not removed
Package 'openjdk-12-jre-headless' is not installed, so not removed
Package 'openjdk-6-jre' is not installed, so not removed
Package 'openjdk-7-jre' is not installed, so not removed
Package 'openjdk-9-jre' is not installed, so not removed
Package 'openjdk-jre' is not installed, so not removed
Package 'openjdk-11-jre-dcevm' is not installed, so not removed
Package 'openjdk-11-dbg' is not installed, so not removed
Package 'openjdk-11-doc' is not installed, so not removed
Package 'openjdk-11-jdk' is not installed, so not removed
Package 'openjdk-11-jre' is not installed, so not removed
Package 'openjdk-11-source' is not installed, so not removed
Package 'openjdk-11-demo' is not installed, so not removed
Package 'openjdk-11-jre-zero' is not installed, so not removed
Package 'openjdk-17-dbg' is not installed, so not removed
Package 'openjdk-17-demo' is not installed, so not removed
Package 'openjdk-17-doc' is not installed, so not removed
Package 'openjdk-17-jdk' is not installed, so not removed
Package 'openjdk-17-jdk-headless' is not installed, so not removed
Package 'openjdk-17-jre' is not installed, so not removed
Package 'openjdk-17-jre-headless' is not installed, so not removed
Package 'openjdk-17-jre-zero' is not installed, so not removed
Package 'openjdk-17-source' is not installed, so not removed
Package 'openjdk-18-dbg' is not installed, so not removed
Package 'openjdk-18-demo' is not installed, so not removed
Package 'openjdk-18-doc' is not installed, so not removed
Package 'openjdk-18-jdk' is not installed, so not removed
Package 'openjdk-18-jdk-headless' is not installed, so not removed
Package 'openjdk-18-jre' is not installed, so not removed
Package 'openjdk-18-jre-headless' is not installed, so not removed
Package 'openjdk-18-jre-zero' is not installed, so not removed
Package 'openjdk-18-source' is not installed, so not removed
Package 'openjdk-19-dbg' is not installed, so not removed
Package 'openjdk-19-demo' is not installed, so not removed
Package 'openjdk-19-doc' is not installed, so not removed
Package 'openjdk-19-jdk' is not installed, so not removed
Package 'openjdk-19-jdk-headless' is not installed, so not removed
Package 'openjdk-19-jre' is not installed, so not removed
Package 'openjdk-19-jre-headless' is not installed, so not removed
Package 'openjdk-19-jre-zero' is not installed, so not removed
Package 'openjdk-19-source' is not installed, so not removed
Package 'openjdk-21-dbg' is not installed, so not removed
Package 'openjdk-21-demo' is not installed, so not removed
Package 'openjdk-21-doc' is not installed, so not removed
Package 'openjdk-21-jdk' is not installed, so not removed
Package 'openjdk-21-jdk-headless' is not installed, so not removed
Package 'openjdk-21-jre' is not installed, so not removed
Package 'openjdk-21-jre-headless' is not installed, so not removed
Package 'openjdk-21-jre-zero' is not installed, so not removed
Package 'openjdk-21-source' is not installed, so not removed
Package 'openjdk-21-testsupport' is not installed, so not removed
Package 'openjdk-8-dbg' is not installed, so not removed
Package 'openjdk-8-demo' is not installed, so not removed
Package 'openjdk-8-doc' is not installed, so not removed
Package 'openjdk-8-jdk' is not installed, so not removed
Package 'openjdk-8-jdk-headless' is not installed, so not removed
Package 'openjdk-8-jre' is not installed, so not removed
Package 'openjdk-8-jre-headless' is not installed, so not removed
Package 'openjdk-8-jre-zero' is not installed, so not removed
Package 'openjdk-8-source' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  java-common libpcsclite1
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ca-certificates-java openjdk-11-jdk-headless openjdk-11-jre-headless
0 upgraded, 0 newly installed, 3 to remove and 35 not upgraded.
After this operation, 258 MB disk space will be freed.
(Reading database ... 126435 files and directories currently installed.)
Removing openjdk-11-jdk-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Removing openjdk-11-jre-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Removing ca-certificates-java (20190909ubuntu1.2) ...
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Get:4 https://cli.github.com/packages stable/main amd64 Packages [346 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,807 kB]
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,336 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,681 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,299 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [5,526 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [5,779 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,577 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,274 kB]
Fetched 33.7 MB in 5s (6,890 kB/s)
Reading package lists...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates-java fonts-dejavu-core fonts-dejavu-extra
  libatk-wrapper-java libatk-wrapper-java-jni libxt-dev libxtst6 libxxf86dga1
  openjdk-17-jdk-headless openjdk-17-jre openjdk-17-jre-headless x11-utils
Suggested packages:
  libxt-doc openjdk-17-demo openjdk-17-source visualvm libnss-mdns
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  ca-certificates-java fonts-dejavu-core fonts-dejavu-extra
  libatk-wrapper-java libatk-wrapper-java-jni libxt-dev libxtst6 libxxf86dga1
  openjdk-17-jdk openjdk-17-jdk-headless openjdk-17-jre
  openjdk-17-jre-headless x11-utils
0 upgraded, 13 newly installed, 0 to remove and 43 not upgraded.
Need to get 125 MB of archives.
After this operation, 287 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jre-headless amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [48.3 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 ca-certificates-java all 20190909ubuntu1.2 [12.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jre amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [232 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jdk-headless amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [71.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jdk amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [1,522 kB]
Fetched 125 MB in 9s (14.1 MB/s)
Selecting previously unselected package openjdk-17-jre-headless:amd64.
(Reading database ... 125976 files and directories currently installed.)
Preparing to unpack .../00-openjdk-17-jre-headless_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jre-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../01-ca-certificates-java_20190909ubuntu1.2_all.deb ...
Unpacking ca-certificates-java (20190909ubuntu1.2) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../02-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../03-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../04-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../05-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../06-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../07-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../08-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../09-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-17-jre:amd64.
Preparing to unpack .../10-openjdk-17-jre_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jre:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-17-jdk-headless:amd64.
Preparing to unpack .../11-openjdk-17-jdk-headless_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jdk-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-17-jdk:amd64.
Preparing to unpack .../12-openjdk-17-jdk_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jdk:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Setting up ca-certificates-java (20190909ubuntu1.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-17-jre-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jpackage to provide /usr/bin/jpackage (jpackage) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up openjdk-17-jre:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Setting up openjdk-17-jdk-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode

In [5]:
!pip install --upgrade pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (3.5.1)
Collecting pyspark
  Downloading pyspark-4.0.1.tar.gz (434.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.2/434.2 MB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.9 (from pyspark)
  Downloading py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Downloading py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.0/203.0 kB 17.0 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-4.0.1-py2.py3-none-any.whl size=434813800 sha256=53115085e3ba24d432644dbee5a5ee7eea00a4147edc67142d5a4e0cc5cb5425
  Stored in directory: /root/.cache/pip/wheels/31/9f/68/f89fb34ccd886909be7d0e390eaaf97f21efdf540c0ee8dbcd
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7
  Attempting uninstall: pyspark
    Found existing installation: pyspark 3.5.1
    Uninstalling pyspark-3.5.1:
      Successfully uninstalled pyspark-3.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 0.8.3 requires pyspark[connect]~=3.5.1, but you have pyspark 4.0.1 which is incompatible.
Successfully installed py4j-0.10.9.9 pyspark-4.0.1

## Dados

**Descrição das colunas:**  
timestamp,user_id,action,adId,campaignId

**Amostra:**  
2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01  
2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02  
2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02  
2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03

**Path:**  
data/ad_action.csv

## Atividade 1

Qual é o anúncio mais popular, ou seja, com mais eventos independente do action?

**Resposta:**  
adId_06

## Atividade 2

Quantos clicks gerou a campanha mais popular?

**Resposta:**  
63983 clicks

## Atividade 3

Algum usuário só visualizou? Quantas actions foram enviadas por usuário que só visualizou?

**Resposta:**  
Sim, o usuário d99871cb-98b7-4ac5-97a5-b9a26c0f897b enviou apenas 1 action

## Atividade 4

Dos 10411 usuários, quantos usuários clicam mais que visualizam?

**Resposta:**  
10078

## Atividade 5

Calcule a quantidade de clicks por dia da semana e apresente o resultado em ordem decrescente de quantidade de clicks.

PS: Nesse exemplo, 0 é segunda-feira e 6 é domingo. Você pode usar outro padrão, contanto que os dias da semana estejam correspondentes a resposta abaixo

**Resposta**  
27918, 4  
25424, 5  
25028, 0  
25027, 3  
25020, 6  
24973, 1  
24915, 2

## Atividade 6

Algum anúncio teve um crescimento de clicks ao longo das 3 campanhas?

**Resposta:**  
Sim, o anúncio adId_07

In [6]:
# IMPORTS, CRIAÇÃO DO CLUSTER E CARREGAMENTO DOS DADOS AQUI
import numpy as np
import os
import pandas as pd
import pyspark.sql.functions as F

from pyspark.sql import SparkSession

os.environ['PYSPARK_SUBMIT_ARGS'] = '\
    --driver-memory 4G \
    --executor-memory 4G \
    pyspark-shell'

In [7]:
# Criando um cluster local com 1 executor e a quantidade de threads igual a quantidade de cores de CPU disponíveis

spark = SparkSession.builder\
    .master("local[*]")\
    .getOrCreate()
spark

In [8]:
# Comando para desativar os recursos do spark
# spark.stop()

In [9]:
AD_ACTION_CSV_PATH = 'drive/MyDrive/data/ad_action.csv'

In [10]:
df = spark.read.csv(AD_ACTION_CSV_PATH, header=False, inferSchema=True)\
  .toDF('timestamp', 'user_id', 'action', 'adId', 'campaignId')
df.show()

+-------------------+--------------------+------+-------+-------------+
|          timestamp|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-09-21 22:11:00|7c74953c-66cc-48b...| click|adId_09|campaignId_01|
|2016-06-25 18:29:00|676a083e-2f8e-4ff...|  view|adId_09|campaignId_02|
|2016-02-14 19:03:00|77158997-0dfa-48b...| click|adId_02|campaignId_02|
|2016-03-26 06:27:00|78aa2467-b502-413...| click|adId_07|campaignId_03|
|2016-01-02 04:57:00|fef9a98c-d73e-48e...|  view|adId_02|campaignId_02|
|2016-03-04 09:14:00|6ba65af9-4d83-456...|  view|adId_09|campaignId_01|
|2016-07-09 21:42:00|be3befb9-ee08-431...| click|adId_09|campaignId_01|
|2016-07-18 21:15:00|d37832ae-546f-4b9...| click|adId_05|campaignId_02|
|2016-04-20 13:30:00|1e5b575e-19e7-44f...| click|adId_03|campaignId_01|
|2016-02-23 19:55:00|ed1b4467-8581-459...|  view|adId_06|campaignId_01|
|2016-10-12 09:51:00|7ebccca0-6039-47b...| click|adId_08|campaignId_02|
|2016-01-30 12:01:00|413f4bb6-1eed-47e...|  view|adId_09|campaignId_02|
|2016-04-30 11:13:00|36b8fffb-66a8-426...| click|adId_02|campaignId_02|
|2016-11-03 09:22:00|f193d313-e475-461...| click|adId_05|campaignId_02|
|2016-02-03 14:09:00|1cb95f66-e5db-497...| click|adId_02|campaignId_03|
|2016-02-25 10:49:00|4a1d1ad6-e404-4f4...| click|adId_06|campaignId_03|
|2016-01-11 04:43:00|c748defa-2451-499...|  view|adId_04|campaignId_03|
|2016-11-12 11:35:00|eec3f831-fe26-450...| click|adId_06|campaignId_02|
|2016-09-26 07:57:00|802efe54-909d-470...| click|adId_09|campaignId_03|
|2016-11-02 08:37:00|99b11329-4d2e-4ce...|  view|adId_06|campaignId_01|
+-------------------+--------------------+------+-------+-------------+
only showing top 20 rows

In [11]:
df.printSchema()

root
 |-- timestamp: timestamp (nullable = true)
 |-- user_id: string (nullable = true)
 |-- action: string (nullable = true)
 |-- adId: string (nullable = true)
 |-- campaignId: string (nullable = true)

## Resposta Atividade 1

Qual é o anúncio mais popular, ou seja, com mais eventos independente do action?

**Resposta:**  
adId_06

In [12]:
# ESCREVA SEU CÓDIGO AQUI

In [23]:
type(df.show())

+-------------------+--------------------+------+-------+-------------+
|          timestamp|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-09-21 22:11:00|7c74953c-66cc-48b...| click|adId_09|campaignId_01|
|2016-06-25 18:29:00|676a083e-2f8e-4ff...|  view|adId_09|campaignId_02|
|2016-02-14 19:03:00|77158997-0dfa-48b...| click|adId_02|campaignId_02|
|2016-03-26 06:27:00|78aa2467-b502-413...| click|adId_07|campaignId_03|
|2016-01-02 04:57:00|fef9a98c-d73e-48e...|  view|adId_02|campaignId_02|
|2016-03-04 09:14:00|6ba65af9-4d83-456...|  view|adId_09|campaignId_01|
|2016-07-09 21:42:00|be3befb9-ee08-431...| click|adId_09|campaignId_01|
|2016-07-18 21:15:00|d37832ae-546f-4b9...| click|adId_05|campaignId_02|
|2016-04-20 13:30:00|1e5b575e-19e7-44f...| click|adId_03|campaignId_01|
|2016-02-23 19:55:00|ed1b4467-8581-459...|  view|adId_06|campaignId_01|
|2016-10-12 09:51:00|7ebccca0-6039-47b...| click|adId_08|campaignId_02|
|2016-01-30 12:01:00|413f4bb6-1eed-47e...|  view|adId_09|campaignId_02|
|2016-04-30 11:13:00|36b8fffb-66a8-426...| click|adId_02|campaignId_02|
|2016-11-03 09:22:00|f193d313-e475-461...| click|adId_05|campaignId_02|
|2016-02-03 14:09:00|1cb95f66-e5db-497...| click|adId_02|campaignId_03|
|2016-02-25 10:49:00|4a1d1ad6-e404-4f4...| click|adId_06|campaignId_03|
|2016-01-11 04:43:00|c748defa-2451-499...|  view|adId_04|campaignId_03|
|2016-11-12 11:35:00|eec3f831-fe26-450...| click|adId_06|campaignId_02|
|2016-09-26 07:57:00|802efe54-909d-470...| click|adId_09|campaignId_03|
|2016-11-02 08:37:00|99b11329-4d2e-4ce...|  view|adId_06|campaignId_01|
+-------------------+--------------------+------+-------+-------------+
only showing top 20 rows

NoneType

In [22]:
type(df.take(1)[0])

pyspark.sql.types.Row

In [24]:
df.show(1)[0]['adId']

+-------------------+--------------------+------+-------+-------------+
|          timestamp|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-09-21 22:11:00|7c74953c-66cc-48b...| click|adId_09|campaignId_01|
+-------------------+--------------------+------+-------+-------------+
only showing top 1 row

TypeError: 'NoneType' object is not subscriptable

In [20]:
df.groupBy('adId')\
  .count()\
  .orderBy(F.desc('count'))\
  .take(1)[0]['adId']

'adId_06'

In [33]:
df.groupBy('adId')\
  .count()\
  .orderBy(F.desc('count'))\
  .first()['adId']

'adId_06'

## Resposta Atividade 2

Quantos clicks gerou a campanha mais popular?

**Resposta:**  
63983 clicks

In [13]:
# ESCREVA SEU CÓDIGO AQUI

In [27]:
df_popular = df.groupBy('campaignId')\
  .count()\
  .orderBy(F.desc('count'))\
  .take(1)[0]['campaignId']
df_popular

'campaignId_02'

In [28]:
#preferi essa
df.where(df.campaignId == df_popular)\
  .where(df.action == 'click')\
  .count()

63983

In [30]:
df.where((F.col('campaignId') == df_popular) & (F.col('action') == "click"))\
  .count()

63983

## Resposta Atividade 3

Algum usuário só visualizou? Quantas actions foram enviadas por usuário que só visualizou?

**Resposta:**  
Sim, o usuário d99871cb-98b7-4ac5-97a5-b9a26c0f897b enviou apenas 1 action

In [14]:
# ESCREVA SEU CÓDIGO AQUI

In [48]:
df.groupBy('user_id', 'action')\
  .count()\
  .groupBy('user_id')\
  .pivot('action')\
  .sum('count')\
  .where(F.col('click').isNull())\
  .toPandas()

                                user_id  click  view
0  d99871cb-98b7-4ac5-97a5-b9a26c0f897b    NaN     1

## Resposta Atividade 4

Dos 10411 usuários, quantos usuários clicam mais que visualizam?

**Resposta:**  
10078

In [15]:
# ESCREVA SEU CÓDIGO AQUI

In [60]:
df.groupBy('user_id', 'action')\
  .count()\
  .groupBy('user_id')\
  .pivot('action')\
  .sum('count')\
  .fillna(0)\
  .where(F.col('click') > F.col('view'))\
  .count()

10078

## Resposta Atividade 5

Calcule a quantidade de clicks por dia da semana e apresente o resultado em ordem decrescente de quantidade de clicks.

PS: Nesse exemplo, 0 é segunda-feira e 6 é domingo. Você pode usar outro padrão, contanto que os dias da semana estejam correspondentes a resposta abaixo

**Resposta**  
27918, 4  
25424, 5  
25028, 0  
25027, 3  
25020, 6  
24973, 1  
24915, 2

In [16]:
# ESCREVA SEU CÓDIGO AQUI

In [65]:
result = df.where(F.col('action') == "click")\
  .withColumn('day_of_week', F.dayofweek('timestamp'))\
  .groupBy('day_of_week')\
  .count()\
  .orderBy(F.desc('count'))

result.toPandas()

   day_of_week  count
0            6  27918
1            7  25424
2            2  25028
3            5  25027
4            1  25020
5            3  24973
6            4  24915

## Resposta Atividade 6

Algum anúncio teve um crescimento de clicks ao longo das 3 campanhas?

**Resposta:**  
Sim, o anúncio adId_07

In [17]:
# ESCREVA SEU CÓDIGO AQUI

In [75]:
result_df= df.where(F.col('action') == "click")\
  .groupBy('adId', 'campaignId')\
  .count()\
  .groupBy('adId')\
  .pivot('campaignId')\
  .sum('count')\
  .fillna(0)\
  .orderBy('adId')

result_df.show()

+-------+-------------+-------------+-------------+
|   adId|campaignId_01|campaignId_02|campaignId_03|
+-------+-------------+-------------+-------------+
|adId_01|         5156|         6452|         5361|
|adId_02|         5073|         7423|         6509|
|adId_03|         5719|         7046|         5197|
|adId_04|         5025|         7023|         6348|
|adId_05|         5518|         6815|         5818|
|adId_06|         5533|         7923|         7074|
|adId_07|         5287|         6909|         7081|
|adId_08|         5451|         6900|         5689|
|adId_09|         5529|         7492|         5857|
|adId_10|         5084|            0|         6013|
+-------+-------------+-------------+-------------+

In [76]:
result_df.where((F.col('campaignId_01') < F.col('campaignId_02')) & (F.col('campaignId_02') < F.col('campaignId_03')))\
  .show()

+-------+-------------+-------------+-------------+
|   adId|campaignId_01|campaignId_02|campaignId_03|
+-------+-------------+-------------+-------------+
|adId_07|         5287|         6909|         7081|
+-------+-------------+-------------+-------------+