In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install --upgrade "dask[dataframe]"

Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.12/dist-packages (2025.9.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (21.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask[dataframe]) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]) (1.17.0)

In [ ]:
!pip install --upgrade "dask[distributed]"

Requirement already satisfied: dask[distributed] in /usr/local/lib/python3.12/dist-packages (2025.9.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (0.12.1)
Requirement already satisfied: distributed==2025.9.0 in /usr/local/lib/python3.12/dist-packages (from dask[distributed]) (2025.9.0)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (1.1.1)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.1.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (6.4.2)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (2.5.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.9.0->dask[distributed]) (3.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->distributed==2025.9.0->dask[distributed]) (3.0.2)

In [ ]:
!pip install --upgrade pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (21.0.0)

## Sobre os dados

O arquivo CSV contém eventos 'click' ou 'view' no tempo, de usuários em anúncios de determinadas campanhas.

**Descrição das colunas:**  
timestamp,user_id,action,adId,campaignId

**Amostra:**  
2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01  
2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02  
2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02  
2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03

**Nome do arquivo CSV:**  
data/ad_action.csv

## Sobre as questões

As questões devem ser respondidas usando a tecnologia Dask.

Quando utilizar pandas tenha cuidado para evitar estouro de memória, sempre imaginado que vai executar o código com uma grande massa de dados.

Mesmo que não consiga terminar alguma questão, favor enviar, porque parte do código pode valer alguma pontuação.

In [ ]:
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)
client

INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.scheduler:State start
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:36703
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:36525'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:39097'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:34623 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:34623
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:45680
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:38819 name: 1
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:38819
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:45696
INFO:distributed.scheduler:Receive client connection: Client-ca870658-92a4-11f0-a8ee-0242ac1c000c
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:45706

In [ ]:
df = dd.read_csv('drive/MyDrive/data/ad_action.csv', header=None, parse_dates=[0])
df.columns = ['timestamp','user_id','action','adId','campaignId']
df

Dask DataFrame Structure:
                    timestamp user_id  action    adId campaignId
npartitions=1
               datetime64[ns]  string  string  string     string
                          ...     ...     ...     ...        ...
Dask Name: operation, 3 expressions
Expr=ColumnsSetter(frame=ArrowStringConversion(frame=FromMapProjectable(df633d0)), columns=['timestamp', 'user_id', 'action', 'adId', 'campaignId'])

In [ ]:
df.head(5)

,timestamp,user_id,action,adId,campaignId
0,2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01
1,2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02
2,2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02
3,2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03
4,2016-01-02 04:57:00,fef9a98c-d73e-48ef-b2cb-766ba85dc3e3,view,adId_02,campaignId_02

## 1) Quais são as top 3 campanhas que geraram mais eventos? Ordene pela quantidade de eventos (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
%%time

df.groupby('campaignId')\
['timestamp']\
.count()\
.rename("events_count")\
.nlargest(3)\
.compute()

CPU times: user 175 ms, sys: 13.6 ms, total: 188 ms
Wall time: 1.83 s

campaignId
campaignId_02    91216
campaignId_03    87036
campaignId_01    76461
Name: events_count, dtype: int64

## 2) Qual campanha teve mais clicks? (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
%%time

df[df['action'] == 'click']\
  .groupby('campaignId')\
  ['timestamp']\
  .count()\
  .rename("clicks_count")\
  .nlargest(1)\
  .compute()

CPU times: user 150 ms, sys: 22.1 ms, total: 172 ms
Wall time: 1.74 s

campaignId
campaignId_02    63983
Name: clicks_count, dtype: int64

## 3) Qual mês teve o maior total de eventos acumulado? (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
df_month = df.copy()
df_month['month'] = df_month['timestamp'].dt.month
df_month.head()

,timestamp,user_id,action,adId,campaignId,month
0,2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01,9
1,2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02,6
2,2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02,2
3,2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03,3
4,2016-01-02 04:57:00,fef9a98c-d73e-48ef-b2cb-766ba85dc3e3,view,adId_02,campaignId_02,1

In [ ]:
%%time
df_month.groupby('month')\
['timestamp']\
.count()\
.rename("events_count")\
.nlargest(1)\
.compute()

CPU times: user 145 ms, sys: 16.6 ms, total: 162 ms
Wall time: 1.87 s

month
1    25800
Name: events_count, dtype: int64

## 4) Nas situações onde existe um evento de view seguido de um evento de click criados pelo mesmo usuário no mesmo anúncio e campanha, quais são os 5 pares de anúncio e campanha com menores médias de tempo entre os dois eventos (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
views = df[df["action"] == "view"].rename(columns={"timestamp": "view_time"})
views.persist()

Dask DataFrame Structure:
                    view_time user_id  action    adId campaignId
npartitions=1
               datetime64[ns]  string  string  string     string
                          ...     ...     ...     ...        ...
Dask Name: read-fused-operation, 1 expression
Expr=FromGraph(d913bfe)

In [ ]:
clicks = df[df["action"] == "click"].rename(columns={"timestamp": "click_time"})
clicks.persist()

Dask DataFrame Structure:
                   click_time user_id  action    adId campaignId
npartitions=1
               datetime64[ns]  string  string  string     string
                          ...     ...     ...     ...        ...
Dask Name: read-fused-operation, 1 expression
Expr=FromGraph(3106115)

In [ ]:
views = views.sort_values("view_time")
clicks = clicks.sort_values("click_time")

In [ ]:
merged = dd.merge_asof(
    views,
    clicks,
    left_on="view_time",
    right_on="click_time",
    by=["user_id", "adId", "campaignId"],
    direction="forward"  # garante que o click venha depois do view
)
merged.head()

,view_time,user_id,action_x,adId,campaignId,click_time,action_y
0,2016-01-01 00:07:00,4fde5dfa-ccde-4c2e-9038-870a21956725,view,adId_07,campaignId_02,2016-02-27 20:47:00,click
1,2016-01-01 00:15:00,218dc6e2-1621-4b4b-8dbe-a2a8ec6bea99,view,adId_04,campaignId_01,2016-01-02 11:06:00,click
2,2016-01-01 00:20:00,1994f3e6-591b-42a3-ba95-8d56cd070ab9,view,adId_04,campaignId_02,2016-01-19 04:22:00,click
3,2016-01-01 00:27:00,9b3b575a-4c7a-4a16-8a9c-dbb55a183a8f,view,adId_01,campaignId_01,2016-03-01 17:42:00,click
4,2016-01-01 00:28:00,ae224ccd-b186-487f-9178-d17a6d01e9d8,view,adId_07,campaignId_03,2016-01-01 08:33:00,click

In [ ]:
merged.isnull().sum().compute()

view_time        0
user_id          0
action_x         0
adId             0
campaignId       0
click_time    4438
action_y      4438
dtype: int64

In [ ]:
merged = merged.dropna(subset=["click_time"])

In [ ]:
merged["diff_seconds"] = (
    merged["click_time"] - merged["view_time"]
).dt.total_seconds()

In [ ]:
medias = merged.groupby(['user_id',"adId", "campaignId"])["diff_seconds"].mean()
medias.nsmallest(5).compute()

user_id                               adId     campaignId
848eb13c-6881-45a3-bd62-05422be20cad  adId_05  campaignId_02     480.0
f4db1c5e-7780-4beb-a36f-1322743d99d5  adId_05  campaignId_02     660.0
28c5def5-3ede-4ead-ac85-13c1819ead4b  adId_01  campaignId_01     960.0
c67d4a61-a911-4982-a685-33664bdcbd76  adId_06  campaignId_02    1140.0
ed526924-2c66-470d-a2eb-622eee5e114f  adId_05  campaignId_01    1320.0
Name: diff_seconds, dtype: float64