In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!java --version

openjdk 11.0.28 2025-07-15
OpenJDK Runtime Environment (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

In [ ]:
!pip list | grep pyspark

pyspark                               3.5.1

In [ ]:
# Remove old Java
!apt-get remove openjdk-* -y

# Install OpenJDK 17
!apt-get update -q
!apt-get install openjdk-17-jdk -y

# Set JAVA_HOME
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

# Verify
!java -version

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'openjdk-11-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-18-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-21-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-19-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-8-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-7-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-testsupport' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-9-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-17-source' for glob 'openjdk-*'
Note, selecting 'openjdk-17-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-11-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-source' for glob 'openjdk-*'
Note, selecting 'openjdk-14-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-13-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-11-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-dcevm' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-12-jre-headless' for glob 'openjdk-*'
Package 'openjdk-6-jre-headless' is not installed, so not removed
Package 'openjdk-14-jre-headless' is not installed, so not removed
Package 'openjdk-13-jre-headless' is not installed, so not removed
Package 'openjdk-12-jre-headless' is not installed, so not removed
Package 'openjdk-6-jre' is not installed, so not removed
Package 'openjdk-7-jre' is not installed, so not removed
Package 'openjdk-9-jre' is not installed, so not removed
Package 'openjdk-jre' is not installed, so not removed
Package 'openjdk-11-jre-dcevm' is not installed, so not removed
Package 'openjdk-11-dbg' is not installed, so not removed
Package 'openjdk-11-doc' is not installed, so not removed
Package 'openjdk-11-jdk' is not installed, so not removed
Package 'openjdk-11-jre' is not installed, so not removed
Package 'openjdk-11-source' is not installed, so not removed
Package 'openjdk-11-demo' is not installed, so not removed
Package 'openjdk-11-jre-zero' is not installed, so not removed
Package 'openjdk-17-dbg' is not installed, so not removed
Package 'openjdk-17-demo' is not installed, so not removed
Package 'openjdk-17-doc' is not installed, so not removed
Package 'openjdk-17-jdk' is not installed, so not removed
Package 'openjdk-17-jdk-headless' is not installed, so not removed
Package 'openjdk-17-jre' is not installed, so not removed
Package 'openjdk-17-jre-headless' is not installed, so not removed
Package 'openjdk-17-jre-zero' is not installed, so not removed
Package 'openjdk-17-source' is not installed, so not removed
Package 'openjdk-18-dbg' is not installed, so not removed
Package 'openjdk-18-demo' is not installed, so not removed
Package 'openjdk-18-doc' is not installed, so not removed
Package 'openjdk-18-jdk' is not installed, so not removed
Package 'openjdk-18-jdk-headless' is not installed, so not removed
Package 'openjdk-18-jre' is not installed, so not removed
Package 'openjdk-18-jre-headless' is not installed, so not removed
Package 'openjdk-18-jre-zero' is not installed, so not removed
Package 'openjdk-18-source' is not installed, so not removed
Package 'openjdk-19-dbg' is not installed, so not removed
Package 'openjdk-19-demo' is not installed, so not removed
Package 'openjdk-19-doc' is not installed, so not removed
Package 'openjdk-19-jdk' is not installed, so not removed
Package 'openjdk-19-jdk-headless' is not installed, so not removed
Package 'openjdk-19-jre' is not installed, so not removed
Package 'openjdk-19-jre-headless' is not installed, so not removed
Package 'openjdk-19-jre-zero' is not installed, so not removed
Package 'openjdk-19-source' is not installed, so not removed
Package 'openjdk-21-dbg' is not installed, so not removed
Package 'openjdk-21-demo' is not installed, so not removed
Package 'openjdk-21-doc' is not installed, so not removed
Package 'openjdk-21-jdk' is not installed, so not removed
Package 'openjdk-21-jdk-headless' is not installed, so not removed
Package 'openjdk-21-jre' is not installed, so not removed
Package 'openjdk-21-jre-headless' is not installed, so not removed
Package 'openjdk-21-jre-zero' is not installed, so not removed
Package 'openjdk-21-source' is not installed, so not removed
Package 'openjdk-21-testsupport' is not installed, so not removed
Package 'openjdk-8-dbg' is not installed, so not removed
Package 'openjdk-8-demo' is not installed, so not removed
Package 'openjdk-8-doc' is not installed, so not removed
Package 'openjdk-8-jdk' is not installed, so not removed
Package 'openjdk-8-jdk-headless' is not installed, so not removed
Package 'openjdk-8-jre' is not installed, so not removed
Package 'openjdk-8-jre-headless' is not installed, so not removed
Package 'openjdk-8-jre-zero' is not installed, so not removed
Package 'openjdk-8-source' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  java-common libpcsclite1
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ca-certificates-java openjdk-11-jdk-headless openjdk-11-jre-headless
0 upgraded, 0 newly installed, 3 to remove and 35 not upgraded.
After this operation, 258 MB disk space will be freed.
(Reading database ... 126441 files and directories currently installed.)
Removing openjdk-11-jdk-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Removing openjdk-11-jre-headless:amd64 (11.0.28+6-1ubuntu1~22.04.1) ...
Removing ca-certificates-java (20190909ubuntu1.2) ...
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
Hit:1 https://cli.github.com/packages stable InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [81.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,808 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [5,609 kB]
Hit:14 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [5,804 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,307 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,371 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,274 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,690 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,577 kB]
Fetched 33.9 MB in 5s (7,373 kB/s)
Reading package lists...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates-java fonts-dejavu-core fonts-dejavu-extra
  libatk-wrapper-java libatk-wrapper-java-jni libxt-dev libxtst6 libxxf86dga1
  openjdk-17-jdk-headless openjdk-17-jre openjdk-17-jre-headless x11-utils
Suggested packages:
  libxt-doc openjdk-17-demo openjdk-17-source visualvm libnss-mdns
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic mesa-utils
The following NEW packages will be installed:
  ca-certificates-java fonts-dejavu-core fonts-dejavu-extra
  libatk-wrapper-java libatk-wrapper-java-jni libxt-dev libxtst6 libxxf86dga1
  openjdk-17-jdk openjdk-17-jdk-headless openjdk-17-jre
  openjdk-17-jre-headless x11-utils
0 upgraded, 13 newly installed, 0 to remove and 38 not upgraded.
Need to get 125 MB of archives.
After this operation, 287 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jre-headless amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [48.3 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 ca-certificates-java all 20190909ubuntu1.2 [12.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2,041 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86dga1 amd64 2:1.1.5-0ubuntu3 [12.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-utils amd64 7.7+5build2 [206 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java all 0.38.0-5build1 [53.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-wrapper-java-jni amd64 0.38.0-5build1 [49.0 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxt-dev amd64 1:1.2.1-1 [396 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jre amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [232 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jdk-headless amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [71.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 openjdk-17-jdk amd64 17.0.16+8~us1-0ubuntu1~22.04.1 [1,522 kB]
Fetched 125 MB in 6s (21.7 MB/s)
Selecting previously unselected package openjdk-17-jre-headless:amd64.
(Reading database ... 125982 files and directories currently installed.)
Preparing to unpack .../00-openjdk-17-jre-headless_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jre-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../01-ca-certificates-java_20190909ubuntu1.2_all.deb ...
Unpacking ca-certificates-java (20190909ubuntu1.2) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../02-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../03-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../04-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../05-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../06-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../07-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../08-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../09-libxt-dev_1%3a1.2.1-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1) ...
Selecting previously unselected package openjdk-17-jre:amd64.
Preparing to unpack .../10-openjdk-17-jre_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jre:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-17-jdk-headless:amd64.
Preparing to unpack .../11-openjdk-17-jdk-headless_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jdk-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Selecting previously unselected package openjdk-17-jdk:amd64.
Preparing to unpack .../12-openjdk-17-jdk_17.0.16+8~us1-0ubuntu1~22.04.1_amd64.deb ...
Unpacking openjdk-17-jdk:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up libxt-dev:amd64 (1:1.2.1-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Setting up ca-certificates-java (20190909ubuntu1.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-17-jre-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jpackage to provide /usr/bin/jpackage (jpackage) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up openjdk-17-jre:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
Setting up openjdk-17-jdk-headless:amd64 (17.0.16+8~us1-0ubuntu1~22.04.1) ...
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode

In [ ]:
!pip install --upgrade pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (3.5.1)
Collecting pyspark
  Downloading pyspark-4.0.1.tar.gz (434.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.2/434.2 MB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.9 (from pyspark)
  Downloading py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Downloading py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.0/203.0 kB 14.0 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-4.0.1-py2.py3-none-any.whl size=434813800 sha256=142e3a5c9e91ddd265eb32c2fd22a9660887d49236eb62c2b718d5237bfba98b
  Stored in directory: /root/.cache/pip/wheels/31/9f/68/f89fb34ccd886909be7d0e390eaaf97f21efdf540c0ee8dbcd
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7
  Attempting uninstall: pyspark
    Found existing installation: pyspark 3.5.1
    Uninstalling pyspark-3.5.1:
      Successfully uninstalled pyspark-3.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dataproc-spark-connect 0.8.3 requires pyspark[connect]~=3.5.1, but you have pyspark 4.0.1 which is incompatible.
Successfully installed py4j-0.10.9.9 pyspark-4.0.1

## Sobre os dados

O arquivo CSV contém eventos 'click' ou 'view' no tempo, de usuários em anúncios de determinadas campanhas.

**Descrição das colunas:**  
timestamp,user_id,action,adId,campaignId

**Amostra:**  
2016-09-21 22:11:00,7c74953c-66cc-48bd-9d02-a02bf039cf3f,click,adId_09,campaignId_01  
2016-06-25 18:29:00,676a083e-2f8e-4ff2-9ec2-270f7f9d6033,view,adId_09,campaignId_02  
2016-02-14 19:03:00,77158997-0dfa-48b7-9149-973dc151ef8d,click,adId_02,campaignId_02  
2016-03-26 06:27:00,78aa2467-b502-413b-94e9-04ec8210bd13,click,adId_07,campaignId_03

**Nome do arquivo CSV:**  
data/ad_action.csv

## Sobre as questões

As questões devem ser respondidas usando alguma API da tecnologia Spark, exceto a API "Pandas API on Spark".

Quando utilizar uma action do Spark tenha cuidado para evitar estouro de memória, sempre imaginado que vai executar o código com uma grande massa de dados.

Mesmo que não consiga terminar alguma questão, favor enviar, porque parte do código pode valer alguma pontuação.

In [ ]:
import os
import pyspark.sql.functions as F
import pyspark.sql.types as T

from pyspark.sql import SparkSession

os.environ['PYSPARK_SUBMIT_ARGS'] = '\
    --driver-memory 2G \
    --executor-memory 2G \
    pyspark-shell'

In [ ]:
spark = SparkSession.builder\
    .master("local[*]")\
    .getOrCreate()
data_spark = spark.read.csv('drive/MyDrive/data/ad_action.csv', header=False, inferSchema=True)\
    .toDF('timestamp', 'user_id', 'action', 'adId', 'campaignId')
data_spark.printSchema()

root
 |-- timestamp: timestamp (nullable = true)
 |-- user_id: string (nullable = true)
 |-- action: string (nullable = true)
 |-- adId: string (nullable = true)
 |-- campaignId: string (nullable = true)

In [ ]:
data_spark.show(5)

+-------------------+--------------------+------+-------+-------------+
|          timestamp|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-09-21 22:11:00|7c74953c-66cc-48b...| click|adId_09|campaignId_01|
|2016-06-25 18:29:00|676a083e-2f8e-4ff...|  view|adId_09|campaignId_02|
|2016-02-14 19:03:00|77158997-0dfa-48b...| click|adId_02|campaignId_02|
|2016-03-26 06:27:00|78aa2467-b502-413...| click|adId_07|campaignId_03|
|2016-01-02 04:57:00|fef9a98c-d73e-48e...|  view|adId_02|campaignId_02|
+-------------------+--------------------+------+-------+-------------+
only showing top 5 rows

In [ ]:
# Descomente para desligar clusters

# spark.stop()

## 1) Quais são as top 3 campanhas que geraram mais eventos? Ordene pela quantidade de eventos (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
data_spark.groupBy('campaignId')\
.count()\
.orderBy('count', ascending=False)\
.limit(3)\
.toPandas()

      campaignId  count
0  campaignId_02  91216
1  campaignId_03  87036
2  campaignId_01  76461

## 2) Qual campanha teve mais clicks? (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
data_spark.where(F.col('action')=='click')\
.groupBy('campaignId')\
.count()\
.orderBy('count', ascending=False)\
.take(1)[0]['campaignId']

'campaignId_02'

## 3) Qual mês teve o maior total de eventos acumulado? (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
df_month = data_spark.withColumn('month', F.month('timestamp'))
df_month.show(5)

+-------------------+--------------------+------+-------+-------------+-----+
|          timestamp|             user_id|action|   adId|   campaignId|month|
+-------------------+--------------------+------+-------+-------------+-----+
|2016-09-21 22:11:00|7c74953c-66cc-48b...| click|adId_09|campaignId_01|    9|
|2016-06-25 18:29:00|676a083e-2f8e-4ff...|  view|adId_09|campaignId_02|    6|
|2016-02-14 19:03:00|77158997-0dfa-48b...| click|adId_02|campaignId_02|    2|
|2016-03-26 06:27:00|78aa2467-b502-413...| click|adId_07|campaignId_03|    3|
|2016-01-02 04:57:00|fef9a98c-d73e-48e...|  view|adId_02|campaignId_02|    1|
+-------------------+--------------------+------+-------+-------------+-----+
only showing top 5 rows

In [ ]:
df_month.groupBy('month')\
.count()\
.orderBy('count', ascending=False)\
.limit(1)\
.toPandas()

   month  count
0      1  25800

## 4) Nas situações onde existe um evento de view seguido de um evento de click criados pelo mesmo usuário no mesmo anúncio e campanha, quais são os 5 pares de anúncio e campanha com menores médias de tempo entre os dois eventos (2,5 pontos)

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [ ]:
views = data_spark.where(F.col('action')=='view').withColumnRenamed('timestamp', 'view_time')\
.orderBy('view_time')
views.show(5)

+-------------------+--------------------+------+-------+-------------+
|          view_time|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-01-01 00:07:00|4fde5dfa-ccde-4c2...|  view|adId_07|campaignId_02|
|2016-01-01 00:15:00|218dc6e2-1621-4b4...|  view|adId_04|campaignId_01|
|2016-01-01 00:20:00|1994f3e6-591b-42a...|  view|adId_04|campaignId_02|
|2016-01-01 00:27:00|9b3b575a-4c7a-4a1...|  view|adId_01|campaignId_01|
|2016-01-01 00:28:00|ae224ccd-b186-487...|  view|adId_07|campaignId_03|
+-------------------+--------------------+------+-------+-------------+
only showing top 5 rows

In [ ]:
clicks = data_spark.where(F.col('action')=='click').withColumnRenamed('timestamp', 'click_time')\
.orderBy('click_time')
clicks.show(5)

+-------------------+--------------------+------+-------+-------------+
|         click_time|             user_id|action|   adId|   campaignId|
+-------------------+--------------------+------+-------+-------------+
|2016-01-01 00:00:00|c577e717-1be3-4e6...| click|adId_06|campaignId_02|
|2016-01-01 00:07:00|0fb092f2-6721-4dd...| click|adId_10|campaignId_03|
|2016-01-01 00:11:00|2dbd9392-768e-4ba...| click|adId_03|campaignId_03|
|2016-01-01 00:12:00|cd3e0222-0796-450...| click|adId_09|campaignId_01|
|2016-01-01 00:13:00|909401e9-55ef-4dd...| click|adId_02|campaignId_01|
+-------------------+--------------------+------+-------+-------------+
only showing top 5 rows

In [ ]:
from pyspark.sql import Window

In [ ]:
#tem todas as possibilidades de view_time -> click_time para o mesmo user_id, adId, campaignId
joined = views.join(
    clicks,
    on=["user_id", "adId", "campaignId"],
    how="left"
)
joined.show(5)

+--------------------+-------+-------------+-------------------+------+-------------------+------+
|             user_id|   adId|   campaignId|          view_time|action|         click_time|action|
+--------------------+-------+-------------+-------------------+------+-------------------+------+
|39ba8e01-f1bb-491...|adId_02|campaignId_03|2016-01-01 09:26:00|  view|2016-08-03 11:29:00| click|
|39ba8e01-f1bb-491...|adId_02|campaignId_03|2016-01-01 09:26:00|  view|2016-12-28 10:35:00| click|
|39ba8e01-f1bb-491...|adId_02|campaignId_03|2016-01-01 09:26:00|  view|2016-12-04 21:53:00| click|
|39ba8e01-f1bb-491...|adId_02|campaignId_03|2016-01-01 09:26:00|  view|2016-04-24 20:26:00| click|
|39ba8e01-f1bb-491...|adId_02|campaignId_03|2016-01-01 09:26:00|  view|2016-08-21 09:06:00| click|
+--------------------+-------+-------------+-------------------+------+-------------------+------+
only showing top 5 rows

In [ ]:
# apenas as combinações em que click_time acontece depois do view_time
filtered = joined.where(F.col("click_time") > F.col("view_time"))
filtered.show(5)

+--------------------+-------+-------------+-------------------+------+-------------------+------+
|             user_id|   adId|   campaignId|          view_time|action|         click_time|action|
+--------------------+-------+-------------+-------------------+------+-------------------+------+
|d9ad512e-274f-41a...|adId_06|campaignId_02|2016-01-01 03:25:00|  view|2016-01-04 08:11:00| click|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-07-25 09:41:00|  view|2016-12-07 22:18:00| click|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-02-25 17:05:00|  view|2016-12-07 22:18:00| click|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-07-25 09:57:00|  view|2016-12-07 22:18:00| click|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-09-06 20:06:00|  view|2016-12-07 22:18:00| click|
+--------------------+-------+-------------+-------------------+------+-------------------+------+
only showing top 5 rows

In [ ]:
# Cria uma coluna com a diferença de tempo entre view e click (em segundos)
diffed = filtered.withColumn(
    "diff_seconds",
    F.unix_timestamp("click_time") - F.unix_timestamp("view_time")
)
diffed.show(5)

+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+
|             user_id|   adId|   campaignId|          view_time|action|         click_time|action|diff_seconds|
+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+
|d9ad512e-274f-41a...|adId_06|campaignId_02|2016-01-01 03:25:00|  view|2016-01-04 08:11:00| click|      276360|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-07-25 09:41:00|  view|2016-12-07 22:18:00| click|    11709420|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-02-25 17:05:00|  view|2016-12-07 22:18:00| click|    24729180|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-07-25 09:57:00|  view|2016-12-07 22:18:00| click|    11708460|
|40969830-24a3-4d3...|adId_01|campaignId_02|2016-09-06 20:06:00|  view|2016-12-07 22:18:00| click|     7956720|
+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+
only showing top 5 rows

In [ ]:
# Define uma janela particionada por usuário, anúncio, campanha e view_time,
# ordenando pelos menores intervalos de tempo (diff_seconds).
# Isso garante que, para cada view, vamos olhar os clicks subsequentes e escolher o mais próximo.
w = Window.partitionBy("user_id", "adId", "campaignId", "view_time") \
          .orderBy(F.col("diff_seconds").asc())

# atribui um número de linha (row_number) dentro de cada partição.
# O click mais próximo do view recebe rn = 1.
ranked = diffed.withColumn("rn", F.row_number().over(w)) \
               .where(F.col("rn") == 1)
ranked.show(5)

+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+---+
|             user_id|   adId|   campaignId|          view_time|action|         click_time|action|diff_seconds| rn|
+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+---+
|0031aa2d-5988-402...|adId_03|campaignId_03|2016-03-11 20:24:00|  view|2016-03-11 21:12:00| click|        2880|  1|
|0031aa2d-5988-402...|adId_03|campaignId_03|2016-04-05 11:17:00|  view|2016-04-06 09:51:00| click|       81240|  1|
|0031aa2d-5988-402...|adId_03|campaignId_03|2016-04-10 10:31:00|  view|2016-04-10 21:08:00| click|       38220|  1|
|0031aa2d-5988-402...|adId_03|campaignId_03|2016-04-10 19:20:00|  view|2016-04-10 21:08:00| click|        6480|  1|
|0031aa2d-5988-402...|adId_03|campaignId_03|2016-07-14 16:22:00|  view|2016-08-14 20:43:00| click|     2694060|  1|
+--------------------+-------+-------------+-------------------+------+-------------------+------+------------+---+
only showing top 5 rows

In [ ]:
#Agrupa por par (user_id,adId, campaignId) e calculamos a média do tempo entre view e click
avg_times = ranked.groupBy('user_id',"adId", "campaignId") \
                  .agg(F.avg("diff_seconds").alias("avg_diff"))
avg_times.show(5)

+--------------------+-------+-------------+------------------+
|             user_id|   adId|   campaignId|          avg_diff|
+--------------------+-------+-------------+------------------+
|0031aa2d-5988-402...|adId_03|campaignId_03|          635940.0|
|00355f85-a403-4fc...|adId_06|campaignId_03|         3289350.0|
|00437ba9-82bd-41a...|adId_05|campaignId_01|         1414980.0|
|0061c33e-b346-4c6...|adId_03|campaignId_02|3868993.3333333335|
|00640825-4c67-4ec...|adId_09|campaignId_01|2261413.3333333335|
+--------------------+-------+-------------+------------------+
only showing top 5 rows

In [ ]:
#Ordenamos pela menor média e pegamos os 5 primeiros pares.
result = avg_times.orderBy("avg_diff").limit(5)
result.toPandas()

                                user_id     adId     campaignId  avg_diff
0  848eb13c-6881-45a3-bd62-05422be20cad  adId_05  campaignId_02     480.0
1  f4db1c5e-7780-4beb-a36f-1322743d99d5  adId_05  campaignId_02     660.0
2  28c5def5-3ede-4ead-ac85-13c1819ead4b  adId_01  campaignId_01     960.0
3  c67d4a61-a911-4982-a685-33664bdcbd76  adId_06  campaignId_02    1140.0
4  ed526924-2c66-470d-a2eb-622eee5e114f  adId_05  campaignId_01    1320.0