In [2]:
import pandas as pd

In [4]:
from sqlalchemy import create_engine

In [22]:
#FORMA MANUAL

In [6]:
Produto = pd.read_excel(r"E:\ETL\Origem\arquivos_excel\Produto.xlsx")

In [10]:
Produto.head()

   ID                  Name  Price  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   4   Vestido Super curto     57            0

In [12]:
Categoria  = pd.read_excel(r"E:\ETL\Origem\arquivos_excel\Categoria.xlsx")

In [14]:
Categoria.head()

   id                     Nome
0   0        Moda e Acessórios
1   1  Cosméticos e Perfumaria
2   2         Eletrodomésticos
3   3                   Livros
4   4                Celulares

In [44]:
engine = create_engine("postgresql+psycopg2://postgres:Naruto120@localhost:5432/testes")

In [18]:
tabelas = {
    "produtos": Produto,
    "categorias": Categoria
}

In [20]:
for nome_tabela, df in tabelas.items():
    df.to_sql(
        name=nome_tabela,
        con=engine,
        if_exists="replace",  # ou "append", se quiser acrescentar
        index=False
    )
    print(f"Tabela {nome_tabela} carregada com sucesso!")

Tabela produtos carregada com sucesso!
Tabela categorias carregada com sucesso!

In [26]:
#FORMA AUTOMATIZADA:

In [46]:
pasta = r"E:\ETL\Origem\arquivos_excel"

In [48]:
import os

In [56]:
for arquivo in os.listdir(pasta):
    if arquivo.endswith(".xlsx"):
        nome_tabela = arquivo.replace(".xlsx", "").lower()
        df = pd.read_excel(os.path.join(pasta, arquivo))
        df.to_sql(nome_tabela, engine, if_exists="replace", index=False)
        print(f"Tabela {nome_tabela} criada a partir de {arquivo}")

Tabela caquinha criada a partir de Caquinha.xlsx
Tabela categoria criada a partir de Categoria.xlsx
Tabela ordens criada a partir de Ordens.xlsx
Tabela produto criada a partir de Produto.xlsx
Tabela vendasproj2 criada a partir de VendasProj2.xlsx