In [1]:
import os
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Colab Notebooks/English Premier League (football) 10 Seasons'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
files = [f for f in os.listdir(file_path) if f.endswith(".csv")]

unique_columns = set()

for f in files:
    df = pd.read_csv(os.path.join(file_path, f))
    unique_columns.update(df.columns)

print("📌 TOTAL DE COLUNAS ÚNICAS:", len(unique_columns))
print("\n📌 LISTA COMPLETA DE COLUNAS:")
for col in sorted(unique_columns):
    print(col)

📌 TOTAL DE COLUNAS ÚNICAS: 77

📌 LISTA COMPLETA DE COLUNAS:
AC
AF
AR
AS
AST
AY
AwayTeam
B365A
B365D
B365H
BSA
BSD
BSH
BWA
BWD
BWH
Bb1X2
BbAH
BbAHh
BbAv<2.5
BbAv>2.5
BbAvA
BbAvAHA
BbAvAHH
BbAvD
BbAvH
BbMx<2.5
BbMx>2.5
BbMxA
BbMxAHA
BbMxAHH
BbMxD
BbMxH
BbOU
Date
Div
FTAG
FTHG
FTR
GBA
GBD
GBH
HC
HF
HR
HS
HST
HTAG
HTHG
HTR
HY
HomeTeam
IWA
IWD
IWH
LBA
LBD
LBH
PSA
PSCA
PSCD
PSCH
PSD
PSH
Referee
SBA
SBD
SBH
SJA
SJD
SJH
VCA
VCD
VCH
WHA
WHD
WHH

In [ ]:

# colunas desejadas
keep_cols = ["FTAG", "FTHG", "Date", "AwayTeam", "HomeTeam"]

for f in files:
    full_path = os.path.join(file_path, f)

    # Lê CSV com todos os tipos como string (evita problemas)
    df = pd.read_csv(full_path, dtype=str)

    # Extrair season do nome (sempre 4 dígitos)
    season = f.split("-")[1].split("_")[0].zfill(4)
    df["season"] = season

    # Mantém só as colunas desejadas
    df = df[keep_cols + ["season"]]

    # Preenche nulos com string vazia
    df = df.fillna("")

    # Salvar tratado
    output_path = os.path.join(file_path, f"cleaned_{f}")
    df.to_csv(output_path, index=False)

    print(f"✔ Arquivo limpo: cleaned_{f}")

✔ Arquivo limpo: cleaned_season-1314_csv.csv
✔ Arquivo limpo: cleaned_season-1112_csv.csv
✔ Arquivo limpo: cleaned_season-1718_csv.csv
✔ Arquivo limpo: cleaned_season-1213_csv.csv
✔ Arquivo limpo: cleaned_season-0910_csv.csv
✔ Arquivo limpo: cleaned_season-1819_csv.csv
✔ Arquivo limpo: cleaned_season-1516_csv.csv
✔ Arquivo limpo: cleaned_season-1415_csv.csv
✔ Arquivo limpo: cleaned_season-1011_csv.csv
✔ Arquivo limpo: cleaned_season-1617_csv.csv

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/English Premier League (football) 10 Seasons/cleaned_season-0910_csv.csv')
df.head()

   FTAG  FTHG        Date    AwayTeam     HomeTeam  season
0     2     0  2009-08-15       Wigan  Aston Villa     910
1     2     0  2009-08-15    Man City    Blackburn     910
2     1     0  2009-08-15  Sunderland       Bolton     910
3     1     2  2009-08-15        Hull      Chelsea     910
4     6     1  2009-08-15     Arsenal      Everton     910

In [ ]:
df['season']="S910"
df.head()

   FTAG  FTHG        Date    AwayTeam     HomeTeam season
0     2     0  2009-08-15       Wigan  Aston Villa   S910
1     2     0  2009-08-15    Man City    Blackburn   S910
2     1     0  2009-08-15  Sunderland       Bolton   S910
3     1     2  2009-08-15        Hull      Chelsea   S910
4     6     1  2009-08-15     Arsenal      Everton   S910

In [ ]:
df1 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/English Premier League (football) 10 Seasons/cleaned_season-1011_csv.csv')
df1.head()

   FTAG  FTHG      Date    AwayTeam     HomeTeam  season
0     0     3  14/08/10    West Ham  Aston Villa    1011
1     0     1  14/08/10     Everton    Blackburn    1011
2     0     0  14/08/10      Fulham       Bolton    1011
3     0     6  14/08/10   West Brom      Chelsea    1011
4     2     2  14/08/10  Birmingham   Sunderland    1011

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

# Formatando para o padrão DD/MM/YY
df['Date'] = df['Date'].dt.strftime('%d/%m/%y')

In [ ]:
df.head()

   FTAG  FTHG      Date    AwayTeam     HomeTeam season
0     2     0  15/08/09       Wigan  Aston Villa   S910
1     2     0  15/08/09    Man City    Blackburn   S910
2     1     0  15/08/09  Sunderland       Bolton   S910
3     1     2  15/08/09        Hull      Chelsea   S910
4     6     1  15/08/09     Arsenal      Everton   S910

In [ ]:
df.to_csv('/content/drive/My Drive/Colab Notebooks/English Premier League (football) 10 Seasons/cleaned_season-0910_csv.csv', index=False)
print(f"✔ Arquivo limpo: cleaned_season-0910")

✔ Arquivo limpo: cleaned_season-0910